name: desktop_nextmind
description: "Aplicação Desktop do Projeto Nextmind."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: any
  http: any
  shared_preferences: any
  syncfusion_flutter_charts: any
  window_manager: any
  syncfusion_flutter_pdfviewer: any
  fl_chart: 
  file_picker: 
  pdf: 
  provider: 
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/